# upstream did not publish any tags, and a performance-critical
# fix appears after the last bump (for 0.0.3). This is what e.g.
# torchtext uses upstream (installing through git), so we add a ".1"
{% set version = "0.0.3.1" %}
{% set commit = "f1998b72a941d1e5f9578a66dc1c20b01913caab" %}

package:
  name: revtok
  version: {{ version }}

source:
  url: https://github.com/jekbradbury/revtok/archive/{{ commit }}.tar.gz
  sha256: a7447fefb44fbe46140bfc337c6ec756b869c37f737fd18eaec1293d15865b8f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tqdm
test:
  requires:
    - python {{ python_min }}
  imports:
    - revtok

about:
  home: https://github.com/jekbradbury/revtok
  license: MIT
  license_file: LICENSE
  summary: Reversible tokenization in Python.
  dev_url: https://github.com/jekbradbury/revtok

extra:
  recipe-maintainers:
    - h-vetinari
